provider:
  name: cloudflare

sources:
  - gateway-httproute

domainFilters:
  - korvintech.cloud

policy: sync

registry: txt
txtOwnerId: homelab

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: api-token